const ALERT="ALERT";
const REFETCH_CHATS="REFETCH_CHATS";

const NEW_ATTACHMENTS="NEW_ATTACHMENTS";
const NEW_MSG_ALERT="NEW_MSG_ALERT";

const NEW_MSG="New Message";
const NEW_REQUEST="NEW_REQUEST"

module.exports={ALERT,REFETCH_CHATS,NEW_MSG_ALERT,NEW_ATTACHMENTS,NEW_REQUEST,NEW_MSG}